favicon: images/logo3.png
banner: /images/webstack_banner_cn.png

logo:
  expanded: images/logo2.png
  collapsed: images/logo3.png
  dark: images/logo2.png

flag:
  - name: Chinese
    default: true
    icon: flag-cn
    index: /index.html
  

search: true

userDefinedSearchData:
  custom: true
  thisSearch: https://www.google.com/search?q=
  thisSearchIcon: url(https://www.google.com/favicon.ico)
  hotStatus: true
  data:
    - name: 百度
      img: url(https://www.baidu.com/favicon.ico)
      url: https://www.baidu.com/s?wd=
    - name: 谷歌
      img: url(https://www.google.com/favicon.ico)
      url: https://www.google.com/search?q=

#githubCorner: '<a href="https://github.com/HCLonely/hexo-theme-webstack" class="github-corner" aria-label="View source on GitHub"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#151513; color:#fff; position: absolute; top: 0; border: 0; right: 0;" aria-hidden="true"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>'

expandAll: false
menu:
  - name: 站长推荐
    icon: far fa-star
    config: testPage
  - name: 常用工具
    icon: far fa-star
    config: hotTools
  - name: 影视资源
    icon: far fa-star
    config: movie  
  - name: 其他工具
    icon: fas fa-tools
    submenu:
      - name: 开发工具
        icon: fas fa-tools
        config: devTools
      - name: AI工具
        icon: fas fa-tools
        config: aiTools
      - name: 我的博客
        icon: fas fa-blog
        config: myBlog
      - name: 友情链接
        icon: fas fa-blog
        config: FriendlyLink
#推荐
testPage:
  - name: 谷歌
    url: https://www.google.com/
    img: /images/ico/favicon.ico
    description: 好用的搜索引擎,需要魔法
  - name: hexo博客框架
    url: https://hexo.io/zh-cn/index.html
    img: /images/ico/hexo.png
    description: 快速、简洁且高效的博客框架
  - name: Deepl翻译
    url: https://www.deepl.com/translator
    img: /images/ico/deepl.png
    description: 全世界最精准的翻译
  - name: bilibili大学
    url: https://www.bilibili.com/
    img: https://www.bilibili.com/favicon.ico?v=1
    description: bilibili-干杯

#常用工具
hotTools:
  - name: Namesilo
    url: https://www.namesilo.com/
    img: https://www.namesilo.com/favicon.ico
    description: 超低价格的国外域名购买网站
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 面向开源及私有软件项目的托管平台。
  - name: GPT
    url: https://chat.openai.com/
    img: https://cdn.oaistatic.com/_next/static/media/favicon-32x32.be48395e.png
    description: chatGPT
  - name: Git学习网站
    url: https://learngitbranching.js.org/?locale=zh_CN
    img: https://learngitbranching.js.org/assets/favicon.ico
    description: 学习git,一个就够
  - name: Cloudflare
    url: https://dash.cloudflare.com/
    img: https://dash.cloudflare.com/apple-touch-icon-57x57.png
    description: 域名解析
  - name: sms-activate
    url: https://sms-activate.org/cn
    img: https://smsactivate.s3.eu-central-1.amazonaws.com/assets/img/activate_favicon32.png
    description: 虚拟号码服务
  - name: sms-bus
    url: https://sms-bus.com/
    img: https://sms-bus.com/favicon.ico
    description: 虚拟号码服务
  - name: picx
    url: https://picx.xpoet.cn/
    img: https://picx.xpoet.cn/logo.png
    description: 好用的全自动构建github图床工具
    
#开发工具
devTools:
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 面向开源及私有软件项目的托管平台。
  - name: vercel
    url: https://vercel.com/
    img: /images/ico/vercel.ico
    description: github项目部署网站
#ai工具
aiTools:
  - name: colab
    url: https://colab.research.google.com/
    img: https://ssl.gstatic.com/colaboratory-static/common/f179726407f6c50bdd169964a71633dd/img/favicon.ico
    description: 谷歌免费算力
  - name: 百度飞浆
    url: https://aistudio.baidu.com/index
    img: https://paddlepaddle-org-cn.cdn.bcebos.com/paddle-site-front/favicon-64.png
    description: 人工智能学习与实训社区
  - name: 科研者之家
    url: https://www.home-for-researchers.com/#/
    img: https://www.home-for-researchers.com/static/img/favicon.ico
    description: AI写作助手助您科研写作
  - name: Midjourney
    url: https://www.midjourney.com/home?callbackUrl=%2Fexplore
    img: https://www.midjourney.com/favicon-32x32.png
    description: 目前最强的ai绘画工具

# Analysis


# Baidu Analytics
# https://tongji.baidu.com/web/welcome/login
baidu_analytics:

# Google Analytics
# https://analytics.google.com/analytics/web/
google_analytics: G-JF6HGZKQE9

# Cloudflare Analytics
# https://www.cloudflare.com/zh-tw/web-analytics/
cloudflare_analytics:

# Microsoft Clarity
# https://clarity.microsoft.com/
microsoft_clarity:

# Advertisement
# --------------------------------------

# Google Adsense (谷歌廣告)
google_adsense:
  enable: true
  auto_ads: true
  js: https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
  client: ca-pub-9555136258724083
  enable_page_level_ads: true

# Insert ads manually (手動插入廣告)
# ad:
#   index:
#   aside:
#   post:

# Verification (站長驗證)
# --------------------------------------
  
  

myBlog:
  - name: KXHH Blog
    url: https://www.cfra.top/
    img: images/LOGO.jpg
    description: 天道酬勤
FriendlyLink:
  - name: yaya Blog
    url: https://www.dazhuangcn.top/
    img: https://www.dazhuangcn.top/img/111.jpg
    description: 游戏资讯
  - name: XP导航网
    url: https://www.xiaopengw.com/
    img: https://www.xiaopengw.com/wp-content/uploads/2023/07/cropped-xiaopengwlogo-1-32x32.png
    description: 内容齐全

about:
  url: /about/
  icon: far fa-heart
  name: 关于本站

aboutPage:
  website:
    head: 关于本站
    html: '<blockquote><p>本站是KXHH在生活学习中精心收集的一些工具,希望能对你有所帮助！</p></blockquote>'
  webmaster:
    head: 关于站长
    name: KXHH
    url: https://www.cfra.top/
    img: images/LOGO.jpg
    description: 访问我的博客
    

since: 2023

busuanzi:
  enable: true
  position: sidebar # 'footer','sidebar'
  pv: 本站总访问量$pv
  uv: 本站总访客数$uv

custom:
  head: |- # 以下内容插入到<head></head>标签内，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->
  body: |- # 以下内容插入到</body>标签之前，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->

js:
  header: /js/header.js
  footer: /js/footer.js
  jquery: /js/jquery-1.11.1.min.js
  bootstrap: /js/bootstrap.min.js
  TweenMax: /js/TweenMax.min.js
  resizeable: /js/resizeable.min.js
  joinable: /js/joinable.js
  xenonApi: /js/xenon-api.min.js
  xenonToggles: /js/xenon-toggles.min.js
  xenonCustom: /js/xenon-custom.min.js
  lozad: /js/lozad.min.js
  html5shiv: /js/html5shiv.min.js
  respond: /js/respond.min.js
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

css:
  hclonely: /css/hclonely.css
  fonts: //fonts.loli.net/css?family=Arimo:400,700,400italic
  linecons: /css/fonts/linecons/css/linecons.min.css
  fontawesome: /css/fonts/fontawesome/css/all.min.css
  bootstrap: /css/bootstrap.min.css
  xenonCore: /css/xenon-core.min.css
  xenonComponents: /css/xenon-components.min.css
  xenonSkins: /css/xenon-skins.min.css
  nav: /css/nav.min.css
